In [19]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error


model_skl = LinearRegression()
data = load_diabetes()
X,y = data['data'], data['target']

X_tr, X_ts, y_tr, y_ts = train_test_split(X,y, test_size=0.1)

model_skl.fit(X_tr, y_tr)


yp_tr = model_skl.predict(X_tr)
yp_ts = model_skl.predict(X_ts)

mae_tr = mean_absolute_error(y_tr, yp_tr)
mae_ts = mean_absolute_error(y_ts, yp_ts)

mse_tr = mean_squared_error(y_tr, yp_tr)
mse_ts = mean_squared_error(y_ts, yp_ts)

print(f'mean_absolute_error (train) = ', mae_tr)
print(f'mean_absolute_error (test) = ', mae_ts)
print(f'mean_squared_error (train) = ', mse_tr)
print(f'mean_squared_error (test) = ', mse_ts)


mean_absolute_error (train) =  42.58150286469087
mean_absolute_error (test) =  49.52943032546134
mean_squared_error (train) =  2792.2748450151744
mean_squared_error (test) =  3583.641005831011


### Ordinary Least Squares

We aim to minimize the following:

$\underset{w}{min}  || Xw - y  ||^2_2$

In [37]:
import jax
from jax import random
import jax.numpy as jnp

key = random.PRNGKey(42)
random.uniform(key, (42,42))

Array([[0.68842983, 0.6349189 , 0.5514072 , ..., 0.7141757 , 0.7775229 ,
        0.9108833 ],
       [0.5065378 , 0.9319916 , 0.4177115 , ..., 0.5091853 , 0.0412364 ,
        0.8537271 ],
       [0.819216  , 0.32981408, 0.77336264, ..., 0.68158305, 0.2845446 ,
        0.20979393],
       ...,
       [0.755849  , 0.8738791 , 0.10128927, ..., 0.7318649 , 0.16407311,
        0.48635995],
       [0.3691144 , 0.12325811, 0.43423176, ..., 0.35124767, 0.8821726 ,
        0.8462212 ],
       [0.74026585, 0.02841198, 0.02599502, ..., 0.53718305, 0.87090695,
        0.14787889]], dtype=float32)

In [ ]:
import jax
from jax import random
import jax.numpy as jnp

class LinearRegressionJax:

    def __init__():
        pass

    def fit(X: jnp.array,
            y: jnp.array) -> self:
        
        self.coef = jn

    def predict(X):
        pass

In [28]:
jnp.arange(10) ** 2

Array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [29]:
jnp.arange(10) * jnp.arange(10).T

Array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)